// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {

    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRxUzGd6syEOFNTzHrsqwc-OjKufHsvTk',
    appId: '1:613930439145:web:fb521a972e5376d0e93b78',
    messagingSenderId: '613930439145',
    projectId: 'tpi-mybi',
    authDomain: 'tpi-mybi.firebaseapp.com',
    storageBucket: 'tpi-mybi.appspot.com',
    measurementId: 'G-MH4022M28M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX9hqJUQ0-4uzC4OGOA16hfXJioUoMxtc',
    appId: '1:613930439145:android:b1a9decc33e4b2a8e93b78',
    messagingSenderId: '613930439145',
    projectId: 'tpi-mybi',
    storageBucket: 'tpi-mybi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7FLcp2gx6U1NIq2fd5W-MxUeYIwvVqsk',
    appId: '1:613930439145:ios:38c88f41f3685c28e93b78',
    messagingSenderId: '613930439145',
    projectId: 'tpi-mybi',
    storageBucket: 'tpi-mybi.appspot.com',
    iosBundleId: 'com.example.tpiMybi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7FLcp2gx6U1NIq2fd5W-MxUeYIwvVqsk',
    appId: '1:613930439145:ios:9ea1a2f63922637be93b78',
    messagingSenderId: '613930439145',
    projectId: 'tpi-mybi',
    storageBucket: 'tpi-mybi.appspot.com',
    iosBundleId: 'com.example.tpiMybi.RunnerTests',
  );
}
