// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6db8nYgoLZ3imLHL-FYEvlMJHFqb9_2U',
    appId: '1:43223098487:web:425bfcdaf8d2b07b38d272',
    messagingSenderId: '43223098487',
    projectId: 'flutterfire-ui-codelab-f8b88',
    authDomain: 'flutterfire-ui-codelab-f8b88.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-f8b88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTw4qr7WZ3xlaqxbzk7QNzghjoispq1dc',
    appId: '1:43223098487:android:3110d6f7019eed5f38d272',
    messagingSenderId: '43223098487',
    projectId: 'flutterfire-ui-codelab-f8b88',
    storageBucket: 'flutterfire-ui-codelab-f8b88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY0j2-rguGn1c8qV8Uu42XsqLG6KbopcE',
    appId: '1:43223098487:ios:e24e43910699d44e38d272',
    messagingSenderId: '43223098487',
    projectId: 'flutterfire-ui-codelab-f8b88',
    storageBucket: 'flutterfire-ui-codelab-f8b88.appspot.com',
    iosBundleId: 'com.example.lalabiProject',
  );
}
